version: "3.8"

services:
  android:
    build:
      context: Platforms/Android/
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/kvm
    tty: true
    stdin_open: true
